auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: killingwolf.com
url: http://killingwolf.com
feed: /atom.xml
author_info: <a href="http://killingwolf.com/">killingwolf</a>
